### ISSUE TITLE
(Read carefully bro) Bro, pls, give maintenance to red_hawk:

### ISSUE THREAD

**Issue by Darkrevengehack** [Zaeem20/FREE_PROXIES_LIST#1]
bro, before you read the below, you have to know that your red_hawk tool does not work well with robots.txt (link robots.txt not detected by red_hawk: http://www.fchopinartes.com/web/robots.txt), the waf detect, and the cms detect, Since in this case and with another link that I use, the robots.txt did not detect it, neither did the cms, instead other tools did detect it, this in http, neither in https, fix it pls, the same what the messages that appear below this message
Link: http://www.fchopinartes.com/web/xmlrpc.php

S U B N E T   C A L C U L A T I O N
====================================

error check your api query

W H O I S   L O O K U P
========================

nothing appears here

D N S   L O O K U P
===================

error input invalid - enter IP or Hostname

G E O  I P  L O O K  U P
=========================

[i] error input invalid. enter IP address.

S Q L   V U L N E R A B I L I T Y   S C A N N E R
===================================================

nothing appears here

**Comment by Zaeem20** [comment]
@Darkrevengehack I marked your words, soon we will release a patch for it. but can you please create issue in RED_HAWK repo
